version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin       # Usuario para autenticación
      MONGO_INITDB_ROOT_PASSWORD: admin   # Contraseña para autenticación
      MONGO_INITDB_DATABASE: mongo            # Nombre de la base de datos
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
